config/routes.rb
Rails.application.routes.draw do
  # root 'shows#index'
  get '/shows/:id/destroy', to: 'shows#destroy'
  get '/acts/:id/destroy', to: 'shows#destroy'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  authenticated :user do
    root 'home#index', as: 'authenticated_root'
		# root 'shows#index', as: 'authenticated_root'
  end
  
	devise_scope :user do
		root 'devise/sessions#new'
  end
  
  # get 'shows/today', :to => 'shows#today'
  # get 'shows/this_week', :to => 'shows#this_week'
  # get 'shows/:id/acts/new', :to => 'acts#new'
  
  resources :shows, :only => [:index, :show, :edit, :update, :destroy, :create, :new]
  resources :acts, :only => [:destroy, :edit, :update, :show, :create]
  
  # resources :users do
  #   resources :shows, :only => [:new]
  # end
  
  resources :shows do
    resources :acts, :only => [:new, :index]
  end
  
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :user
  has_many :act_shows
  has_many :acts, :through => :act_shows
   
  
  validates_uniqueness_of :date, :message => "That date is already taken.  Please choose another."
  validates_presence_of :start_time, :message => "Please enter a valid start time"
  validates_presence_of :date, :message => "Please enter a valid date"
  
  # scope :today_confirmed, -> { where(confirmed: true) }
  scope :today_all, -> { where("date = ?", Date.today) }


  def format_confirmed
    if self.confirmed
      "Yes"
    else
      "No"
    end
  end
  

  def self.confirmed_shows_by_date
    Show.all.select{|show| show.confirmed}.sort{|a,b| a.date <=> b.date}
  end
    
  def self.shows_by_date
    Show.all.sort{ |a,b| a.date <=> b.date}
  end

  # def self.today_confirmed
  #   t = Date.today
  #   Show.all.detect{ |show| (show.date == t) && show.confirmed}
  # end

  # def self.today_all
  #   t = Date.today
  #   Show.all.detect{ |show| show.date == t}
  # end

  def self.this_week_confirmed
    oneWeek = Date.today + 7
    Show.all.select{|show| (show.date < oneWeek) && show.confirmed }.sort{|a,b| a.date <=> b.date}
  end

  def self.this_week_all
    oneWeek = Date.today + 7
    Show.all.select{|show| show.date < oneWeek}.sort{|a,b| a.date <=> b.date}
  end


  


end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :find_show, only:[:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @shows = Show.shows_by_date
      render json: @shows
    else
      @shows = Show.confirmed_shows_by_date
      render json: @shows
    end
  end
  
  def show
    render json: @show
  end

  def today
    if user_signed_in?
      @show = Show.today_all.first
      
    else
      @show = Show.today_confirmed
    end
  end

  def this_week
    if user_signed_in?
      @shows = Show.this_week_all
    else
      @shows = Show.this_week_confirmed
    end
  end

  def new
    @show = Show.new
    render partial: 'form', locals: { show: @show }, layout: false 
  end

  def create
    params[:show].parse_time_select! :start_time
    show = Show.new(show_params)
    show.user_id = current_user.id if current_user
    if show.save
      render json: show, status: 201
        # format.html { redirect_to show_path(@show), notice: 'Show was successfully created.' }
    else
        format.html {render :new, notice: 'Errors were found.' }
    end
  end

  def edit
  end

  def update
    params[:show].parse_time_select! :start_time
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @show.destroy
    ActShow.where(:show_id => @show.id).destroy_all
    respond_to do |format|
      format.html { redirect_to shows_path , notice: 'Show was successfully deleted.' }
    end
  end

  private

  def find_show
    @show = Show.find(params[:id])
  end

  def show_params
    params.require(:show).permit(:date, :start_time, :confirmed, :user_id, :act_id, :notes)
  end


end

app/helpers/shows_helper.rb
module ShowsHelper

  def format_date(show)
    show.date.strftime("%B %e, %Y")
  end

  def format_time(show)
    show.start_time.strftime("%l:%M %p")
  end


end

app/views/shows/_form.html.erb
<% if @show.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>
 
    <ul>
    <% @show.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @show do |f| %>

  <div class="form-group"> <%= f.label :date %><br>
  <%= f.date_select(:date, :order => [:month, :day, :year]) %></div>

  <div class="form-group"><%= f.label :start_time %><br>
  <%= f.time_select :start_time,
    :combined => true,
    :default => Time.now.change(:hour => 11, :min => 30),
    :minute_interval => 30,
    :time_separator => "",
    :start_hour => 16,
    :start_minute => 30,
    :end_hour => 23,
    :ampm => true,
    :end_minute => 30
   %></div>

  <div class="form-group"><%= f.label :confirmed %><br>
  <%= f.check_box :confirmed %></div>

  <div class="form-group"><%= f.label :notes %><br>
  <%= f.text_area :notes %></div>
  
  <div class="btn btn-primary">
    <%= f.submit 'Add Show', :id => 'show_submit' %>
  </div>
<% end %>

app/views/shows/_shows.html.erb
<ul>

  <% @shows.each do |s| %>
    <li>
  <%= link_to "#{format_date(s)}", s %>
    </li>
  <% end %>


<ul>

app/views/shows/_thisweek.html.erb
<ul>
  <% @shows.map do |show| %>
    <li><%= link_to "#{format_date(show)}", show %></li>
  <% end %>
</ul>

app/views/shows/_todaysshows.html.erb
<% if @show %>
    <p><strong>Today's Show:</strong></p>
    <p><strong><%= format_date(@show) %> - <%= format_time(@show) %></strong></p>
    
    <% if @show.acts.count > 0 %>
      <% @show.acts.each do |act| %>
        <%= ActShow.setOrder(act, @show) %>:
        <%= link_to "#{act.name}", act_path(act) %>
        <br>
      <% end %>
    
    <% else %>
      <p>There are no currently scheduled acts.</p>
    <% end %>

<% else %>
  <p>There is no show scheduled today!</p>
<% end %>
  

app/views/shows/edit.html.erb
<h1>Edit <%= @show.date %> </h1>

<%= render 'form' %>

<%= link_to "Cancel", shows_path %>

app/views/shows/index.html.erb
<p><strong><%= link_to "Click to view today's show:", shows_today_path %></strong></p>
<p><strong><%= link_to "Click to view this week's shows:", shows_this_week_path %></strong></p>

<p><strong>All Shows:</strong></p>
<%= render 'shows' %>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form' %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="info">
    <p><strong>Date:</strong> <%= format_date(@show) %></p>
    <p><strong>Start Time:</strong> <%= format_time(@show) %></p>
    <p><strong><%= link_to "Acts:", show_acts_path(@show) %></strong></p>
    
    <% if @show.acts.count > 0 %>
      <% @show.acts.each do |act| %>
          <%= ActShow.setOrder(act, @show) %>: 
          <%= link_to "#{act.name}", act_path(act) %>
          <br>
      <% end %>
    <% else %>
      <li><p>No acts yet!</p></li>
    <% end %>

    <p><strong>Confirmed? </strong> <%= @show.format_confirmed %></p>
    <p><strong>Notes:</strong> <%= @show.notes %> </p>
    <% if user_signed_in? %>
      <p><%= link_to 'Add Act', new_show_act_path(@show.id)  %>
      <p><%= link_to 'Edit Date, time, or add notes', [:edit, @show] %></p>
      <p><%= link_to 'Delete Show', show_path(@show), method: :delete  %></p>
    <% end %>
    <%= link_to 'Back', shows_path %></p>
  </div>
</div>

app/views/shows/this_week.html.erb
<p><strong>This Week's Shows</strong></p>
<%= render 'thisweek' %><br>
<%= link_to 'back', root_path %>

app/views/shows/today.html.erb
<%= render 'todaysshows' %>