config/routes.rb
Rails.application.routes.draw do
  # root 'shows#index'
  get '/shows/:id/destroy', to: 'shows#destroy'
  get '/acts/:id/destroy', to: 'shows#destroy'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  authenticated :user do
    root 'home#index', as: 'authenticated_root'
		# root 'shows#index', as: 'authenticated_root'
  end
  
	devise_scope :user do
		root 'devise/sessions#new'
  end
  
  # get 'shows/today', :to => 'shows#today'
  # get 'shows/this_week', :to => 'shows#this_week'
  # get 'shows/:id/acts/new', :to => 'acts#new'
  
  resources :shows, :only => [:index, :show, :edit, :update, :destroy, :create, :new]
  resources :acts, :only => [:destroy, :edit, :update, :show, :create]
  
  # resources :users do
  #   resources :shows, :only => [:new]
  # end
  
  resources :shows do
    resources :acts, :only => [:new, :index]
  end
  
end

app/models/act.rb
class Act < ApplicationRecord
  # belongs_to :show
  has_many :act_shows, :dependent => :destroy
  has_many :shows, :through => :act_shows  
  accepts_nested_attributes_for :act_shows, allow_destroy: true

  validates :name,
            :presence => {:message => "Name can't be blank."},
            :uniqueness => {:message => "Name already exists."}

  validates :contact_name, :presence => {:message => "Please enter a contact name" }
  validates :contact_email, :presence =>  {:message => "Please enter a contact email"}
  
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_action :find_act, only:[:show, :edit, :update, :destroy]
  before_action :find_show, only:[:index]

  def index
    @show = Show.find(params[:show_id])
  end

  def show
  end  

  def new
    show = Show.find(params[:show_id])
    @act = show.acts.create
    render partial: 'form', locals: { act: @act, show_id: show }, layout: false
  end


  def create 
  act = Act.new(act_params)
    if act.save
      render json: act, status: 201
    else
      @show = Show.last
      format.html {redirect_to show_path(@show), notice: 'Errors were found.' }
    end
  end
  
  def edit 
  end
  
  def update
    respond_to do |format|
      if @act.update(act_params)
        format.html { redirect_to act_path(@act), notice: 'Act was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  
  def destroy
    ActShow.where("act_id = ?", @act.id).destroy_all
    @act.destroy
    respond_to do |format|
      format.html {redirect_to shows_path, notice: 'Act was successfully deleted. '}
    end
  end
  
  private
  
  def find_act
    @act = Act.find(params[:id])
  end
  
  def find_show
    @show = Show.find(params[:show_id])
  end

  def act_params
    params.require(:act).permit(:name, :website, :blurb, :contact_name, :contact_email, :notes, :collectionName, act_shows_attributes: [:headliner, :show_id])
  end

  def set_set_order(act, show)
     # get the specific line on ActShow
     actshow = ActShow.where("act_id = ? and show_id = ?", act.id, show.id).first
     # get all the acts of that specific show
     showInstances = ActShow.where("show_id = ?", show.id)
     if showInstances.count == 1
       actshow.set_order = 1
     else
       # get the highest value in set_order (stripping the newly added nil value and add the value plus one to actshow)
       actshow.set_order = (showInstances.map{|show| show.set_order}.reject{|item| item.nil?}.max) + 1
     end
     actshow.save
  end


end

app/helpers/acts_helper.rb
module ActsHelper
  
  def headliner?(act)
    if ActShow.find(act.id).headliner
      "Yes"
    else
      "No"
    end
  end
end

app/views/acts/_errors.html.erb
<% if @act.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being added:</h2>
 
    <ul>
    <% @act.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/acts/_form.html.erb
 
<%= form_for(@act, :html => {:name => "ActForm"}) do |f| %>
  

  <div class="field"> <%= f.label :name %><br>
  <%= f.text_field :name %></div>

  <div class="field"><%= f.label :website %><br>
  <%= f.text_field :website %></div>

  <div class="field"><%= f.label :blurb %><br>
  <%= f.text_area :blurb %></div>

  <div class="field"><%= f.label :headliner %><br>
  
  <%= f.fields_for :act_shows, @act.act_shows.build do |s| %>
    <%= s.hidden_field :show_id, :value => params[:show_id] %>
    <%= s.check_box :headliner %>
  <% end %></div>

  <div class="field"><%= f.label :contact_name %><br>
  <%= f.text_field :contact_name %></div>

  <div class="field"><%= f.label :contact_email %><br>
  <%= f.email_field :contact_email %></div>
  
  <div class="field"><%= f.label :notes %><br>
  <%= f.text_area :notes %></div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acts/edit.html.erb
<h1>Edit Act</h1>

<%= form_for @act do |f| %>

  <div class="field"> <%= f.label :name %><br>
  <%= f.text_field :name %></div>

  <div class="field"><%= f.label :website %><br>
  <%= f.text_field :website %></div>

  <div class="field"><%= f.label :blurb %><br>
  <%= f.text_area :blurb %></div>

  <div class="field"><%= f.label :contact_name %><br>
  <%= f.text_field :contact_name %></div>

  <div class="field"><%= f.label :contact_email %><br>
  <%= f.email_field :contact_email %></div>
  
  <div class="field"><%= f.label :notes %><br>
  <%= f.text_area :notes %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acts/index.html.erb
<% @show.acts.each do |act| %>
  <strong><%= ActShow.setOrder(act, @show) %> : <%= link_to "#{act.name}", act.website %></strong><br>
  <%= act.blurb %><br>
  <br>
<% end %>

<%= link_to "Back", show_path(@show) %>

app/views/acts/new.html.erb
<h1>New Act</h1>

<%= render 'form' %>

app/views/acts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="info">
<p><strong>Name: </strong><%= @act.name %></p>
<p><strong>Website: </strong> <%= link_to "#{@act.website}", @act.website %>
<p><strong>Blurb: </strong><%= @act.blurb %></p>
<p><strong>Headliner? </strong><%= headliner?(@act) %></p>
<p><strong>Contact Name: </strong><%= @act.contact_name %></p>
<p><strong>Notes: </strong><%= @act.notes %></p>
<p><strong>Contact Email: </strong><%= mail_to @act.contact_email %></p>
<% if user_signed_in? %>
<p><%= link_to 'Delete Act', act_path(@act), method: :delete %></p>
<p><%= link_to 'Edit Act', edit_act_path(@act) %></p>
<% end %>
<p><%= link_to 'Back', shows_path %></p>
</div>